//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasgemPortfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDepartment
    {
        public TblDepartment()
        {
            this.TblEmployee = new HashSet<TblEmployee>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual ICollection<TblEmployee> TblEmployee { get; set; }
    }
}
